version: '3.8'
name: sse-chat-app

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
  vanilla-client:
    build:
      context: ./vanilla-js-client
      dockerfile: Dockerfile.dev
    ports:
      - 5174:5174
    